baseURL = '/'
languageCode = 'en-us'
title = "Leolleo's Digital Garden"
theme = 'terminal'
paginate = 5

[params]
    contentTypeName = 'posts'
    themeColor = 'orange'
    showMenuItems = 2
    showLanguageSelector = false
    fullWidthTheme = false
    centerTheme = true
    showLastUpdated = false

[languages]
  [languages.en]
    languageName = "English"
    title = "(DEV) Leolleo's Digital Garden"
    subtitle = "Powered by Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
