baseURL = '/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Leonardo Prado'
sectionPagesMenu = "main"
disableKinds = ['taxonomy', 'term']
summaryLength = 40

[params]
  dateFormat = 'Jan 02, 2006'
  iconSize = '40px'
  googleAnalyticsTag = 'G-C6FZCFZCC4'

[menu]
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    title = 'Blog'
    pageref = '/blog'
    weight = -110
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    title = 'About'
    pageref = '/about'
    weight = -100

[markup]
  [markup.highlight]
    noClasses = false

[languages]
  [languages.pt-br]
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    title = 'Leonardo Prado'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Leonardo Prado'
    weight = 2
    # [languages.en.params]
      # subtitle = 'Reference, Tutorials, and Explanations'
