on:
  pull_request:
    types:
      - closed

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_PROJECT_NAME: ${{ vars.CF_PROJECT_NAME }}
  GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      ref_name_slug: ${{ steps.ref_name_slug.outputs.this }}
    steps:
      # Taken from https://github.com/rlespinasse/slugify-value/blob/v1.x/slugify.sh
      - id: ref_name_slug
        run: |
          slug=$(\
            echo ${GITHUB_HEAD_REF} \
              | sed -E -e 's!refs/heads!!g' -e 's#refs/[^\/]*/##;s/[^a-zA-Z0-9._-]+/-/g;s/^-*//' -e 's/-*$//' \
          )

          echo "this=${slug}" >> "${GITHUB_OUTPUT}"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: info
    env:
      REF_SLUG: ${{ needs.info.outputs.ref_name_slug }}
    steps:
      - name: Clean UP GitHub envs and Cloudflare Deployments
        working-directory: .github/scripts
        run: ./.github/scripts/clean_up.sh
        shell: bash
