on:
  pull_request:
    types:
      - closed

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_PROJECT_NAME: ${{ vars.CF_PROJECT_NAME }}
  GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

jobs:
  infos:
    runs-on: ubuntu-latest
    outputs:
      infos: ${{ steps.ref_name_slug.outputs }}
    steps:
      - id: infos
        run: ./gen-infos.sh
        working-directory: .github/scripts


  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: infos
    env:
      REF_SLUG: ${{ needs.infos.outputs.infos.ref_name_slug }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean UP GitHub envs and Cloudflare Deployments
        run: ./clean_up.sh
        working-directory: .github/scripts
        shell: bash
