name: Clean UP PR
on:
  pull_request:
    types:
      - closed

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_PROJECT_NAME: ${{ vars.CF_PROJECT_NAME }}
  GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      REF_SLUG: pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean UP GitHub envs and Cloudflare Deployments
        run: ./clean_up.sh
        working-directory: .github/scripts
        shell: bash
