name: main

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LIVE_ENV_NAME: leolleo.dev
  LIVE_ENV_URL: https://leolleo.dev
  PREVIEW_ENV_DOMAIN: garden-cbf.pages.dev

jobs:
  infos:
    runs-on: ubuntu-latest
    outputs:
      infos: ${{ steps.ref_name_slug.outputs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: infos
        run: ./gen_infos.sh
        working-directory: .github/scripts

  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.102.3
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: public

  deploy:
    concurrency:
      group: "${{ needs.infos.outputs.infos.ref_name_slug }}"
      cancel-in-progress: true
    environment:
      name: ${{ needs.infos.outputs.infos.env_name }}
      url: ${{ needs.infos.outputs.infos.url }}
    runs-on: ubuntu-latest
    needs:
      - infos
      - build
    steps:
      - name: Downloads artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: public

      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --branch ${{ needs.infos.outputs.infos.ref_name_slug }} --project-name blog ./public

      - name: Purge cloudflare cache
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/a5f4d54fc54af37e05218d9b4e8cd4d9/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
