# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to CloudFlare pages

env:
  BASE_URL: garden.leolleo.dev

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.102.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: build
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${BASE_URL}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Downloads artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: show info
        shell: bash
        run: |
          ls -l

      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages publish --env production --project-name garden ./public
